os: linux
language: shell
services: docker

jobs:
  include:
    -
      stage: build images
      name: amd64-latest
      arch: amd64
      env: TAG=amd64-latest
      script: docker build --pull --tag mondedie/rutorrent:"${TAG}" .
    -
      name: amd64-filebot
      arch: amd64
      env: TAG=amd64-filebot
      script: docker build --build-arg FILEBOT=true --pull --tag mondedie/rutorrent:"${TAG}" .
    -
      name: arm64-latest
      arch: arm64
      env: TAG=arm64-latest
      script: docker build --pull --file Dockerfile.aarch64 --tag mondedie/rutorrent:"${TAG}" .
    -
      name: arm64-filebot
      arch: arm64
      env: TAG=arm64-filebot
      script: docker build --pull --file Dockerfile.aarch64 --build-arg FILEBOT=true --tag mondedie/rutorrent:"${TAG}" .
    -
      stage: deploy manifest
      name: manifest-tool
      install:
        - wget https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
        - mv manifest-tool-linux-amd64 manifest-tool
        - chmod +x manifest-tool
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - ./manifest-tool push from-spec manifest/latest.yml
        - ./manifest-tool push from-spec manifest/filebot.yml
      after_success: skip

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: docker push mondedie/rutorrent:"${TAG}"
  on:
    branch: master
