os: linux
sudo: required
language: shell

services:
  - docker

before_script:
  - docker pull mondedie/rutorrent:latest
  - docker pull mondedie/rutorrent:filebot

script:
  - docker build --pull --cache-from mondedie/rutorrent:latest --tag mondedie/rutorrent:latest .
  - docker build --pull --cache-from mondedie/rutorrent:filebot --tag mondedie/rutorrent:filebot --build-arg FILEBOT=YES .

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script:
    - docker push mondedie/rutorrent:latest
    - docker push mondedie/rutorrent:filebot
  on:
    branch: master
