os: linux
language: shell

services:
  - docker

jobs:
  include:
    - stage: build tag latest
      script: docker build --pull --tag mondedie/rutorrent:latest .
    - stage: build tag filebot
      script: docker build --pull --tag mondedie/rutorrent:filebot --build-arg FILEBOT=true .

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

deploy:
  provider: script
  script: docker push mondedie/rutorrent:latest && docker push mondedie/rutorrent:filebot
