os: linux
dist: bionic
arch: amd64
language: shell
service: docker

install:
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - sudo apt-get autoremove
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io qemu-user-static
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - ls /proc/sys/fs/binfmt_misc
  - cat /proc/sys/fs/binfmt_misc/qemu-aarch64

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx create --name builder --use
  - docker buildx inspect builder --bootstrap
  - docker buildx build --progress plain --push --pull --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 --tag mondedie/rutorrent:"${TAG}" .

jobs:
  include:
    -
      stage: Build images
      name: Build latest tag
      env: TAG=latest
    -
      name: Build filebot tag
      env: TAG=filebot
