os: linux
arch: amd64
dist: bionic
language: shell
services: docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io qemu-user-static
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d

install:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx create --name builder --use
  - docker buildx inspect builder --bootstrap

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - docker buildx build --pull --platform linux/amd64,linux/arm/v7,linux/arm64/v8 --tag mondedie/rutorrent:"${TAG}" --push .

jobs:
  include:
    -
      stage: Build images
      name: Build the latest tag
      env: TAG=latest
    -
      name: Build the filebot tag
      env: TAG=filebot
