os: linux
language: shell
services: docker

jobs:
  include:
    -
      stage: Build images
      name: Build latest tag
      arch: amd64
      env: TAG=latest
      install:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - sudo apt-get update -y
        - sudo apt-get install -y qemu-user-static
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - docker buildx create --name builder
        - docker buildx inspect builder --bootstrap
        - docker buildx use builder
        - docker buildx build --progress plain --push --pull --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 --tag mondedie/rutorrent:"${TAG}" .
    -
      name: Build filebot tag
      arch: amd64
      env: TAG=filebot
      install:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - sudo apt-get update -y
        - sudo apt-get install -y qemu-user-static
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      script:
        - docker buildx create --name builder
        - docker buildx inspect builder --bootstrap
        - docker buildx use builder
        - docker buildx build --build-arg FILEBOT=true --progress plain --push --pull --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 --tag mondedie/rutorrent:"${TAG}" .
