os: linux
language: shell
services: docker

jobs:
  include:
  - name: latest
    arch: amd64
    env: TAG=amd64-latest
    script: docker build --pull --tag mondedie/rutorrent:"${TAG}" .
  - name: filebot
    arch: amd64
    env: TAG=amd64-filebot
    script: docker build --build-arg FILEBOT=true --pull --tag mondedie/rutorrent:"${TAG}" .
  - name: latest
    arch: arm64
    env: TAG=arm64-latest
    script: docker build --pull --file Dockerfile.aarch64 --tag mondedie/rutorrent:"${TAG}" .
  - name: filebot
    arch: arm64
    env: TAG=arm64-filebot
    script: docker build --pull --file Dockerfile.aarch64 --build-arg FILEBOT=true --tag mondedie/rutorrent:"${TAG}" .

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: docker push mondedie/rutorrent:"${TAG}"
  on:
    branch: master
