name: rutorrent-buildx

on:
  push:
    branches: master

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Dockerhub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Run Buildx latest tag
        run: |
          docker buildx build \
          --pull \
          --push \
          --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 \
          --tag mondedie/rutorrent:latest .
  build-filebot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Dockerhub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Run Buildx filebot tag
        run: |
          docker buildx build \
          --pull \
          --push \
          --build-arg "FILEBOT=true" \
          --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 \
          --tag mondedie/rutorrent:filebot .
